import pandas as pd

configfile: "config/parameters.yaml"

samples = pd.read_csv(
    "config/samples.tsv", sep="\t", dtype=str, keep_default_na=False
).set_index("sample", drop=False)


def sample_fasta(wildcards):
    return samples.loc[wildcards.sample, "fasta"]


def has_gff(sample: str) -> bool:
    return samples.loc[sample, "gff"].strip() != ""


def sample_gff(wildcards):
    return samples.loc[wildcards.sample, "gff"]


def has_sequence_report(sample: str) -> bool:
    return samples.loc[sample, "sequence_report"].strip() != ""


def sample_sequence_report(wildcards):
    return samples.loc[wildcards.sample, "sequence_report"]


include: "rules/headers.smk"
include: "rules/starfish.smk"
include: "rules/minichromosomes.smk"


rule all:
    input:
        expand(
            "results/starfish/{sample}/{sample}_YR.filt.gff",
            sample=config["pilot_samples"],
        ),
        "results/minichromosomes/contig_metrics.tsv",
